name: Manter Render Ativo

on:
  schedule:
    - cron: "2,7,12,17,22,27,32,37,42,47,52,57 * * * *"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Enviar requisição para o Render
        run: |
          curl \
            --fail \
            --silent \
            --show-error \
            --location \
            --max-time 90 \
            --retry 2 \
            --retry-delay 5 \
            "https://samu-192-ntl-pharma.onrender.com/"
